### ISSUE TITLE
Default cover art not scaled to fit frame

### ISSUE THREAD

**Issue by joelrichters** [gogglesmm/gogglesmm#68] opened 2017-04-04 10:27 UTC
_Album browser, cover view:_ for ‘All x Albums’ and albums without cover art, Goggles uses a default image of an optical disc. (Ten years from now kids will be clueless as to what it represents though, like the teenage girl in a YouTube video seeing a floppy disk for the first time in her life: ‘It looks like a save icon!’ LOL)

When using small or medium covers, the image is not scaled to fit the frame and flows over its borders. When using big covers, the image fits within the cover frame. I've seen this behaviour ever since I started using a Goggles version with cover view somewhere in 2015.

I'm using v1.1.7 from the official Goggles Music Manager PPA on (L)Ubuntu 16.04.2.

Thanks for fixing the cover cache bug by the way, I'm glad I don't have to manually erase the cover cache and restart Goggles anymore!

Small covers, bug:
![smallcovers](https://cloud.githubusercontent.com/assets/26896621/24652210/42b48db6-1931-11e7-958b-cd0cd9d10641.png)

Big covers, no bug:
![bigcovers](https://cloud.githubusercontent.com/assets/26896621/24652211/42b71874-1931-11e7-9222-17b21e8c2ba7.png)

**Comment by gogglesguy** [comment] 2017-04-04 23:53
Can you try the following:
Go to the preferences dialog and change the icon theme to another one. See if it the cover icon shows up correctly and switch back to your previous icon theme. Check again if the cover icon is displayed correctly. If the icon now displays correctly, the next time you restart it will be incorrect again.

**Comment by gogglesguy** [comment] 2017-04-05 00:23
We may have to start using a vinyl icon since that's becoming trendy again. :)

**Comment by joelrichters** [comment] 2017-04-05 11:05
Yes, it happens exactly as you described. You don't even have to pick a different icon theme; just opening the drop down menu and clicking the icon theme that was already selected scales the cd image correctly for the rest of the session. After restarting the unscaled image is back.

I guess you fixed this bug with the above commit then :)

**Comment by gogglesguy** [comment] 2017-04-05 14:39
Yes, but due my specific installed icon themes I didn't have a way to reproduce this. Thanks!

**Closed** 2017-04-12 01:42 UTC
Labels: bug

**Comment by gogglesguy** [comment] 2017-04-12 02:09
Available in 1.1.8
